steps:
  - uses: actions/checkout@v2
  - name: Use Node.js
    uses: actions/setup-node@v2
    with:
      node-version: "16.18.1"

  - name: Install dependencies
    run: npm install

  - name: Run test
    run: npm test
